## Step 1: Import the library

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 3.0.2

## Part A: Creating a Series

A Series is a one-dimensional labelled array.

In [2]:
# 1) Series from a Python list (default index 0, 1, 2, ...)
marks = pd.Series([78, 85, 90, 66, 74])
print("Series from a list:")
print(marks)

Series from a list:
0    78
1    85
2    90
3    66
4    74
dtype: int64

In [3]:
# 2) Series with our own index labels
marks = pd.Series([78, 85, 90, 66, 74],
                  index=["Amit", "Riya", "Karan", "Neha", "Raj"],
                  name="Marks")
print("Series with custom index:")
print(marks)

Series with custom index:
Amit     78
Riya     85
Karan    90
Neha     66
Raj      74
Name: Marks, dtype: int64

In [4]:
# 3) Series from a dictionary (keys become the index)
city_population = pd.Series({"Surat": 7.5, "Ahmedabad": 8.4, "Vadodara": 2.2, "Rajkot": 1.9})
print("Series from a dictionary (population in lakhs):")
print(city_population)

Series from a dictionary (population in lakhs):
Surat        7.5
Ahmedabad    8.4
Vadodara     2.2
Rajkot       1.9
dtype: float64

In [5]:
# 4) Useful Series properties and operations
print("Values :", marks.values)
print("Index  :", list(marks.index))
print("Data type :", marks.dtype)
print("Size   :", marks.size)

print("\nSelecting one element by label   ->", marks["Riya"])
print("Selecting one element by position ->", marks.iloc[2])

print("\nMarks after adding 5 grace marks to everyone:")
print(marks + 5)

print("\nMarks greater than 75:")
print(marks[marks > 75])

Values : [78 85 90 66 74]
Index  : ['Amit', 'Riya', 'Karan', 'Neha', 'Raj']
Data type : int64
Size   : 5

Selecting one element by label   -> 85
Selecting one element by position -> 90

Marks after adding 5 grace marks to everyone:
Amit     83
Riya     90
Karan    95
Neha     71
Raj      79
Name: Marks, dtype: int64

Marks greater than 75:
Amit     78
Riya     85
Karan    90
Name: Marks, dtype: int64

In [6]:
# 5) Quick statistics on a Series
print("Mean    :", marks.mean())
print("Maximum :", marks.max(), "(", marks.idxmax(), ")")
print("Minimum :", marks.min(), "(", marks.idxmin(), ")")
print("\nSummary:")
print(marks.describe())

Mean    : 78.6
Maximum : 90 ( Karan )
Minimum : 66 ( Neha )

Summary:
count     5.000000
mean     78.600000
std       9.370165
min      66.000000
25%      74.000000
50%      78.000000
75%      85.000000
max      90.000000
Name: Marks, dtype: float64

## Part B: Creating a DataFrame

A DataFrame is a 2-D table with rows and columns.

In [7]:
# 1) DataFrame from a dictionary (each key = a column)
data = {
    "StudentID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name":      ["Amit", "Riya", "Karan", "Neha", "Raj", "Simran", "Dev", "Anjali", "Rohan", "Pooja"],
    "Branch":    ["CE", "IT", "CE", "IT", "ME", "CE", "ME", "IT", "CE", "ME"],
    "Gender":    ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "Marks":     [78, 85, 90, 66, 74, 88, 59, 92, 71, 83],
    "Attendance":[85, 92, 88, 75, 80, 95, 70, 98, 78, 90],
}

df = pd.DataFrame(data)
df

   StudentID    Name Branch Gender  Marks  Attendance
0          1    Amit     CE      M     78          85
1          2    Riya     IT      F     85          92
2          3   Karan     CE      M     90          88
3          4    Neha     IT      F     66          75
4          5     Raj     ME      M     74          80
5          6  Simran     CE      F     88          95
6          7     Dev     ME      M     59          70
7          8  Anjali     IT      F     92          98
8          9   Rohan     CE      M     71          78
9         10   Pooja     ME      F     83          90

In [8]:
# 2) DataFrame from a list of lists
df_small = pd.DataFrame(
    [["Pen", 10, 50], ["Notebook", 45, 30], ["Bag", 550, 5]],
    columns=["Item", "Price", "Stock"]
)
df_small

       Item  Price  Stock
0       Pen     10     50
1  Notebook     45     30
2       Bag    550      5

In [9]:
# 3) DataFrame from a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd.DataFrame(arr, columns=["A", "B", "C"], index=["r1", "r2", "r3"])

    A  B  C
r1  1  2  3
r2  4  5  6
r3  7  8  9

In [10]:
# 4) DataFrame from several Series
s1 = pd.Series([10, 20, 30], index=["a", "b", "c"])
s2 = pd.Series([1.5, 2.5, 3.5], index=["a", "b", "c"])
pd.DataFrame({"Quantity": s1, "Rate": s2})

   Quantity  Rate
a        10   1.5
b        20   2.5
c        30   3.5

### Exploring the DataFrame

In [11]:
print("Shape (rows, columns):", df.shape)
print("Column names         :", list(df.columns))
print("\nFirst 3 rows:")
display(df.head(3))
print("Last 3 rows:")
display(df.tail(3))

Shape (rows, columns): (10, 6)
Column names         : ['StudentID', 'Name', 'Branch', 'Gender', 'Marks', 'Attendance']

First 3 rows:

   StudentID   Name Branch Gender  Marks  Attendance
0          1   Amit     CE      M     78          85
1          2   Riya     IT      F     85          92
2          3  Karan     CE      M     90          88

Last 3 rows:

   StudentID    Name Branch Gender  Marks  Attendance
7          8  Anjali     IT      F     92          98
8          9   Rohan     CE      M     71          78
9         10   Pooja     ME      F     83          90

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     int64
 1   Name        10 non-null     str
 2   Branch      10 non-null     str
 3   Gender      10 non-null     str
 4   Marks       10 non-null     int64
 5   Attendance  10 non-null     int64
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [13]:
# Summary statistics of numeric columns
df.describe()

       StudentID     Marks  Attendance
count   10.00000  10.00000   10.000000
mean     5.50000  78.60000   85.100000
std      3.02765  10.95648    9.134185
min      1.00000  59.00000   70.000000
25%      3.25000  71.75000   78.500000
50%      5.50000  80.50000   86.500000
75%      7.75000  87.25000   91.500000
max     10.00000  92.00000   98.000000

## Part C: Data Selection

### 1. Selecting columns

In [14]:
# One column -> returns a Series
print(type(df["Name"]))
df["Name"]

<class 'pandas.Series'>

0      Amit
1      Riya
2     Karan
3      Neha
4       Raj
5    Simran
6       Dev
7    Anjali
8     Rohan
9     Pooja
Name: Name, dtype: str

In [15]:
# Many columns -> use a list inside [] -> returns a DataFrame
df[["Name", "Branch", "Marks"]]

     Name Branch  Marks
0    Amit     CE     78
1    Riya     IT     85
2   Karan     CE     90
3    Neha     IT     66
4     Raj     ME     74
5  Simran     CE     88
6     Dev     ME     59
7  Anjali     IT     92
8   Rohan     CE     71
9   Pooja     ME     83

### 2. Selecting rows using `iloc` (by position)
`iloc[row_position, column_position]` – the end number is **not** included.

In [16]:
print("Single row (position 0):")
display(df.iloc[0])

print("Rows 2 to 4:")
display(df.iloc[2:5])

print("Rows 0-2 and columns 1-3:")
display(df.iloc[0:3, 1:4])

Single row (position 0):

StudentID        1
Name          Amit
Branch          CE
Gender           M
Marks           78
Attendance      85
Name: 0, dtype: object

Rows 2 to 4:

   StudentID   Name Branch Gender  Marks  Attendance
2          3  Karan     CE      M     90          88
3          4   Neha     IT      F     66          75
4          5    Raj     ME      M     74          80

Rows 0-2 and columns 1-3:

    Name Branch Gender
0   Amit     CE      M
1   Riya     IT      F
2  Karan     CE      M

### 3. Selecting rows using `loc` (by label)
`loc[row_label, column_label]` – the end label **is** included.

In [17]:
print("Rows 0 to 3 with columns Name and Marks:")
display(df.loc[0:3, ["Name", "Marks"]])

# Make Name the index to select using names
df_named = df.set_index("Name")
print("Details of Riya:")
display(df_named.loc["Riya"])

Rows 0 to 3 with columns Name and Marks:

    Name  Marks
0   Amit     78
1   Riya     85
2  Karan     90
3   Neha     66

Details of Riya:

StudentID      2
Branch        IT
Gender         F
Marks         85
Attendance    92
Name: Riya, dtype: object

In [18]:
# Select a single value
print("Marks of Karan:", df_named.loc["Karan", "Marks"])

Marks of Karan: 90

## Part D: Filtering (selecting rows by condition)

In [19]:
# Students who scored more than 80
df[df["Marks"] > 80]

   StudentID    Name Branch Gender  Marks  Attendance
1          2    Riya     IT      F     85          92
2          3   Karan     CE      M     90          88
5          6  Simran     CE      F     88          95
7          8  Anjali     IT      F     92          98
9         10   Pooja     ME      F     83          90

In [20]:
# Students of the CE branch
df[df["Branch"] == "CE"]

   StudentID    Name Branch Gender  Marks  Attendance
0          1    Amit     CE      M     78          85
2          3   Karan     CE      M     90          88
5          6  Simran     CE      F     88          95
8          9   Rohan     CE      M     71          78

In [21]:
# Multiple conditions -> use & (AND) and | (OR); keep every condition in brackets
print("CE branch AND marks >= 80:")
display(df[(df["Branch"] == "CE") & (df["Marks"] >= 80)])

print("Marks > 85 OR attendance < 75:")
display(df[(df["Marks"] > 85) | (df["Attendance"] < 75)])

CE branch AND marks >= 80:

   StudentID    Name Branch Gender  Marks  Attendance
2          3   Karan     CE      M     90          88
5          6  Simran     CE      F     88          95

Marks > 85 OR attendance < 75:

   StudentID    Name Branch Gender  Marks  Attendance
2          3   Karan     CE      M     90          88
5          6  Simran     CE      F     88          95
6          7     Dev     ME      M     59          70
7          8  Anjali     IT      F     92          98

In [22]:
# isin() -> match any value from a list
print("Students from IT or ME:")
display(df[df["Branch"].isin(["IT", "ME"])])

# between() -> value inside a range
print("Marks between 70 and 85:")
display(df[df["Marks"].between(70, 85)])

# str.startswith() -> filter on text
print("Names starting with 'R':")
display(df[df["Name"].str.startswith("R")])

Students from IT or ME:

   StudentID    Name Branch Gender  Marks  Attendance
1          2    Riya     IT      F     85          92
3          4    Neha     IT      F     66          75
4          5     Raj     ME      M     74          80
6          7     Dev     ME      M     59          70
7          8  Anjali     IT      F     92          98
9         10   Pooja     ME      F     83          90

Marks between 70 and 85:

   StudentID   Name Branch Gender  Marks  Attendance
0          1   Amit     CE      M     78          85
1          2   Riya     IT      F     85          92
4          5    Raj     ME      M     74          80
8          9  Rohan     CE      M     71          78
9         10  Pooja     ME      F     83          90

Names starting with 'R':

   StudentID   Name Branch Gender  Marks  Attendance
1          2   Riya     IT      F     85          92
4          5    Raj     ME      M     74          80
8          9  Rohan     CE      M     71          78

In [23]:
# query() -> another readable way to filter
df.query("Marks > 80 and Attendance > 90")

   StudentID    Name Branch Gender  Marks  Attendance
1          2    Riya     IT      F     85          92
5          6  Simran     CE      F     88          95
7          8  Anjali     IT      F     92          98

In [24]:
# Filtering + selecting only certain columns
df.loc[df["Marks"] > 80, ["Name", "Marks"]]

     Name  Marks
1    Riya     85
2   Karan     90
5  Simran     88
7  Anjali     92
9   Pooja     83

### Adding a new column and sorting

In [25]:
# Create a new column using a condition
df["Result"] = np.where(df["Marks"] >= 60, "Pass", "Fail")      # pass mark = 60 (example)
df["Grade"] = pd.cut(df["Marks"], bins=[0, 60, 70, 80, 90, 100],
                     labels=["D", "C", "B", "A", "A+"])
df

   StudentID    Name Branch Gender  Marks  Attendance Result Grade
0          1    Amit     CE      M     78          85   Pass     B
1          2    Riya     IT      F     85          92   Pass     A
2          3   Karan     CE      M     90          88   Pass     A
3          4    Neha     IT      F     66          75   Pass     C
4          5     Raj     ME      M     74          80   Pass     B
5          6  Simran     CE      F     88          95   Pass     A
6          7     Dev     ME      M     59          70   Fail     D
7          8  Anjali     IT      F     92          98   Pass    A+
8          9   Rohan     CE      M     71          78   Pass     B
9         10   Pooja     ME      F     83          90   Pass     A

In [26]:
# Sort by marks (highest first)
df.sort_values(by="Marks", ascending=False)[["Name", "Branch", "Marks", "Grade"]]

     Name Branch  Marks Grade
7  Anjali     IT     92    A+
2   Karan     CE     90     A
5  Simran     CE     88     A
1    Riya     IT     85     A
9   Pooja     ME     83     A
0    Amit     CE     78     B
4     Raj     ME     74     B
8   Rohan     CE     71     B
3    Neha     IT     66     C
6     Dev     ME     59     D

## Part E: Grouping with `groupby()`

Idea: **Split** the data into groups -> **Apply** a function to each group -> **Combine** the results.

In [27]:
# Average marks of each branch
df.groupby("Branch")["Marks"].mean()

Branch
CE    81.75
IT    81.00
ME    72.00
Name: Marks, dtype: float64

In [28]:
# Number of students in each branch
df.groupby("Branch")["StudentID"].count()

Branch
CE    4
IT    3
ME    3
Name: StudentID, dtype: int64

In [29]:
# Average of several columns
df.groupby("Branch")[["Marks", "Attendance"]].mean().round(2)

        Marks  Attendance
Branch
CE      81.75       86.50
IT      81.00       88.33
ME      72.00       80.00

In [30]:
# Group by TWO columns
df.groupby(["Branch", "Gender"])["Marks"].mean()

Branch  Gender
CE      F         88.000000
        M         79.666667
IT      F         81.000000
ME      F         83.000000
        M         66.500000
Name: Marks, dtype: float64

In [31]:
# Look inside one group
ce_group = df.groupby("Branch").get_group("CE")
ce_group[["Name", "Marks"]]

     Name  Marks
0    Amit     78
2   Karan     90
5  Simran     88
8   Rohan     71

## Part F: Aggregation – `sum`, `mean`, `min`, `max`, `count`, `agg()`

In [32]:
# Aggregation on the whole column
print("Total marks     :", df["Marks"].sum())
print("Average marks   :", df["Marks"].mean())
print("Highest marks   :", df["Marks"].max())
print("Lowest marks    :", df["Marks"].min())
print("Median marks    :", df["Marks"].median())
print("Std deviation   :", round(df["Marks"].std(), 2))
print("Total students  :", df["Marks"].count())

Total marks     : 786
Average marks   : 78.6
Highest marks   : 92
Lowest marks    : 59
Median marks    : 80.5
Std deviation   : 10.96
Total students  : 10

In [33]:
# agg() -> many functions at once
df["Marks"].agg(["min", "max", "mean", "median", "std"]).round(2)

min       59.00
max       92.00
mean      78.60
median    80.50
std       10.96
Name: Marks, dtype: float64

In [34]:
# Different aggregations for different columns
df.agg({"Marks": ["min", "max", "mean"], "Attendance": ["min", "max", "mean"]}).round(2)

      Marks  Attendance
min    59.0        70.0
max    92.0        98.0
mean   78.6        85.1

In [35]:
# groupby + agg -> the most useful combination
summary = df.groupby("Branch").agg(
    Total_Students=("StudentID", "count"),
    Average_Marks=("Marks", "mean"),
    Highest_Marks=("Marks", "max"),
    Lowest_Marks=("Marks", "min"),
    Average_Attendance=("Attendance", "mean"),
).round(2)
summary

,Total_Students,Average_Marks,Highest_Marks,Lowest_Marks,Average_Attendance
Branch,,,,,
CE,4,81.75,90,71,86.50
IT,3,81.00,92,66,88.33
ME,3,72.00,83,59,80.00

In [36]:
# Sort the summary and find the best branch
summary.sort_values("Average_Marks", ascending=False)

,Total_Students,Average_Marks,Highest_Marks,Lowest_Marks,Average_Attendance
Branch,,,,,
CE,4,81.75,90,71,86.50
IT,3,81.00,92,66,88.33
ME,3,72.00,83,59,80.00

In [37]:
best_branch = summary["Average_Marks"].idxmax()
print("Branch with the highest average marks:", best_branch,
      "(", summary["Average_Marks"].max(), ")")

Branch with the highest average marks: CE ( 81.75 )

In [38]:
# Pivot table -> Excel-style summary (Branch as rows, Gender as columns)
pd.pivot_table(df, values="Marks", index="Branch", columns="Gender",
               aggfunc="mean", margins=True).round(2)

Gender     F      M    All
Branch
CE      88.0  79.67  81.75
IT      81.0    NaN  81.00
ME      83.0  66.50  72.00
All     82.8  74.40  78.60

In [39]:
# Count of each category
print("Students per branch:")
print(df["Branch"].value_counts())

print("\nCross-tab of Branch vs Gender:")
pd.crosstab(df["Branch"], df["Gender"])

Students per branch:
Branch
CE    4
IT    3
ME    3
Name: count, dtype: int64

Cross-tab of Branch vs Gender:

Gender  F  M
Branch
CE      1  3
IT      3  0
ME      1  2

## Conclusion

- **Series** were created from a list, a dictionary, and with custom index labels.
- **DataFrames** were created from a dictionary, list of lists, NumPy array and Series.
- **Selection** was performed using `[]`, `iloc` (position) and `loc` (label).
- **Filtering** was performed with conditions (`>`, `==`), `&`, `|`, `isin()`, `between()`, `str.startswith()` and `query()`.
- **Grouping** was performed using `groupby()` on one and two columns.
- **Aggregation** was performed with `sum`, `mean`, `min`, `max`, `count`, `agg()` and `pivot_table()`, giving a branch-wise summary of student performance.