## Step 1: Import the libraries

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 2: Create the dataset

In [2]:
data = {
    "EmpID":      [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name":       ["Amit", "Riya", "Karan", "Neha", "Raj", "Simran", "Dev", "Anjali", "Rohan", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR", "Finance"],
    "Age":        [25, 30, 28, 35, 40, 27, 32, 29, 45, 38],
    "Salary":     [50000, 42000, 55000, 60000, 75000, 40000, 65000, 52000, 48000, 70000],
    "Experience": [2, 5, 3, 10, 15, 2, 8, 4, 20, 12],
}

df = pd.DataFrame(data)
df

   EmpID    Name Department  Age  Salary  Experience
0    101    Amit         IT   25   50000           2
1    102    Riya         HR   30   42000           5
2    103   Karan         IT   28   55000           3
3    104    Neha    Finance   35   60000          10
4    105     Raj         IT   40   75000          15
5    106  Simran         HR   27   40000           2
6    107     Dev    Finance   32   65000           8
7    108  Anjali         IT   29   52000           4
8    109   Rohan         HR   45   48000          20
9    110   Pooja    Finance   38   70000          12

## 1. Slicing – selecting rows and columns

In [3]:
# Select a single column
print("Single column (Name):")
print(df["Name"].head(3))

Single column (Name):
0     Amit
1     Riya
2    Karan
Name: Name, dtype: str

In [4]:
# Select multiple columns (use double brackets)
df[["Name", "Salary"]]

     Name  Salary
0    Amit   50000
1    Riya   42000
2   Karan   55000
3    Neha   60000
4     Raj   75000
5  Simran   40000
6     Dev   65000
7  Anjali   52000
8   Rohan   48000
9   Pooja   70000

In [5]:
# iloc -> selection by POSITION (row number / column number)
print("First 4 rows using iloc:")
display(df.iloc[0:4])

print("Rows 2 to 5, columns 1 to 3 using iloc:")
display(df.iloc[2:6, 1:4])

First 4 rows using iloc:

   EmpID   Name Department  Age  Salary  Experience
0    101   Amit         IT   25   50000           2
1    102   Riya         HR   30   42000           5
2    103  Karan         IT   28   55000           3
3    104   Neha    Finance   35   60000          10

Rows 2 to 5, columns 1 to 3 using iloc:

     Name Department  Age
2   Karan         IT   28
3    Neha    Finance   35
4     Raj         IT   40
5  Simran         HR   27

In [6]:
# loc -> selection by LABEL (index name / column name)
print("Rows 0 to 3 with columns Name and Salary using loc:")
df.loc[0:3, ["Name", "Salary"]]

Rows 0 to 3 with columns Name and Salary using loc:

    Name  Salary
0   Amit   50000
1   Riya   42000
2  Karan   55000
3   Neha   60000

## 2. Filtering – selecting rows by condition

In [7]:
# Employees earning more than 50000
print("Salary > 50000:")
display(df[df["Salary"] > 50000])

# Employees in the IT department
print("Department is IT:")
display(df[df["Department"] == "IT"])

Salary > 50000:

   EmpID    Name Department  Age  Salary  Experience
2    103   Karan         IT   28   55000           3
3    104    Neha    Finance   35   60000          10
4    105     Raj         IT   40   75000          15
6    107     Dev    Finance   32   65000           8
7    108  Anjali         IT   29   52000           4
9    110   Pooja    Finance   38   70000          12

Department is IT:

   EmpID    Name Department  Age  Salary  Experience
0    101    Amit         IT   25   50000           2
2    103   Karan         IT   28   55000           3
4    105     Raj         IT   40   75000          15
7    108  Anjali         IT   29   52000           4

In [8]:
# Multiple conditions: use & (AND), | (OR) and put each condition in brackets
print("IT department AND Salary > 50000:")
display(df[(df["Department"] == "IT") & (df["Salary"] > 50000)])

print("HR OR Finance department:")
display(df[(df["Department"] == "HR") | (df["Department"] == "Finance")])

IT department AND Salary > 50000:

   EmpID    Name Department  Age  Salary  Experience
2    103   Karan         IT   28   55000           3
4    105     Raj         IT   40   75000          15
7    108  Anjali         IT   29   52000           4

HR OR Finance department:

   EmpID    Name Department  Age  Salary  Experience
1    102    Riya         HR   30   42000           5
3    104    Neha    Finance   35   60000          10
5    106  Simran         HR   27   40000           2
6    107     Dev    Finance   32   65000           8
8    109   Rohan         HR   45   48000          20
9    110   Pooja    Finance   38   70000          12

In [9]:
# isin() is a shortcut for checking many values
df[df["Department"].isin(["HR", "Finance"]) & (df["Age"] < 35)]

   EmpID    Name Department  Age  Salary  Experience
1    102    Riya         HR   30   42000           5
5    106  Simran         HR   27   40000           2
6    107     Dev    Finance   32   65000           8

## 3. Sorting

In [10]:
# Sort by Salary (lowest to highest)
print("Ascending order of Salary:")
display(df.sort_values(by="Salary"))

# Sort by Salary (highest to lowest)
print("Descending order of Salary:")
display(df.sort_values(by="Salary", ascending=False))

Ascending order of Salary:

   EmpID    Name Department  Age  Salary  Experience
5    106  Simran         HR   27   40000           2
1    102    Riya         HR   30   42000           5
8    109   Rohan         HR   45   48000          20
0    101    Amit         IT   25   50000           2
7    108  Anjali         IT   29   52000           4
2    103   Karan         IT   28   55000           3
3    104    Neha    Finance   35   60000          10
6    107     Dev    Finance   32   65000           8
9    110   Pooja    Finance   38   70000          12
4    105     Raj         IT   40   75000          15

Descending order of Salary:

   EmpID    Name Department  Age  Salary  Experience
4    105     Raj         IT   40   75000          15
9    110   Pooja    Finance   38   70000          12
6    107     Dev    Finance   32   65000           8
3    104    Neha    Finance   35   60000          10
2    103   Karan         IT   28   55000           3
7    108  Anjali         IT   29   52000           4
0    101    Amit         IT   25   50000           2
8    109   Rohan         HR   45   48000          20
1    102    Riya         HR   30   42000           5
5    106  Simran         HR   27   40000           2

In [11]:
# Sort by more than one column: first Department (A-Z), then Salary (high to low)
df.sort_values(by=["Department", "Salary"], ascending=[True, False])

   EmpID    Name Department  Age  Salary  Experience
9    110   Pooja    Finance   38   70000          12
6    107     Dev    Finance   32   65000           8
3    104    Neha    Finance   35   60000          10
8    109   Rohan         HR   45   48000          20
1    102    Riya         HR   30   42000           5
5    106  Simran         HR   27   40000           2
4    105     Raj         IT   40   75000          15
2    103   Karan         IT   28   55000           3
7    108  Anjali         IT   29   52000           4
0    101    Amit         IT   25   50000           2

## 4. Concatenating – joining DataFrames

In [12]:
# A second DataFrame with new employees (same columns)
new_data = {
    "EmpID":      [111, 112, 113],
    "Name":       ["Kiran", "Meera", "Tarun"],
    "Department": ["IT", "HR", "Finance"],
    "Age":        [26, 31, 36],
    "Salary":     [51000, 46000, 68000],
    "Experience": [3, 6, 11],
}
df_new = pd.DataFrame(new_data)

# Concatenate ROW-wise (stack one below the other)
df_all = pd.concat([df, df_new], ignore_index=True)
print("After row-wise concatenation, shape =", df_all.shape)
df_all

After row-wise concatenation, shape = (13, 6)

    EmpID    Name Department  Age  Salary  Experience
0     101    Amit         IT   25   50000           2
1     102    Riya         HR   30   42000           5
2     103   Karan         IT   28   55000           3
3     104    Neha    Finance   35   60000          10
4     105     Raj         IT   40   75000          15
5     106  Simran         HR   27   40000           2
6     107     Dev    Finance   32   65000           8
7     108  Anjali         IT   29   52000           4
8     109   Rohan         HR   45   48000          20
9     110   Pooja    Finance   38   70000          12
10    111   Kiran         IT   26   51000           3
11    112   Meera         HR   31   46000           6
12    113   Tarun    Finance   36   68000          11

In [13]:
# Concatenate COLUMN-wise (side by side)
extra_cols = pd.DataFrame({
    "City": ["Surat", "Vadodara", "Surat", "Rajkot", "Ahmedabad",
             "Surat", "Rajkot", "Vadodara", "Surat", "Ahmedabad"]
})

df_side = pd.concat([df, extra_cols], axis=1)
df_side

   EmpID    Name Department  Age  Salary  Experience       City
0    101    Amit         IT   25   50000           2      Surat
1    102    Riya         HR   30   42000           5   Vadodara
2    103   Karan         IT   28   55000           3      Surat
3    104    Neha    Finance   35   60000          10     Rajkot
4    105     Raj         IT   40   75000          15  Ahmedabad
5    106  Simran         HR   27   40000           2      Surat
6    107     Dev    Finance   32   65000           8     Rajkot
7    108  Anjali         IT   29   52000           4   Vadodara
8    109   Rohan         HR   45   48000          20      Surat
9    110   Pooja    Finance   38   70000          12  Ahmedabad

## 5. Aggregating – summarizing data

In [14]:
# Overall summary of numeric columns
df[["Age", "Salary", "Experience"]].agg(["min", "max", "mean", "sum"])

        Age    Salary  Experience
min    25.0   40000.0         2.0
max    45.0   75000.0        20.0
mean   32.9   55700.0         8.1
sum   329.0  557000.0        81.0

In [15]:
# Group by Department and calculate the average salary
print("Average salary per department:")
df.groupby("Department")["Salary"].mean()

Average salary per department:

Department
Finance    65000.000000
HR         43333.333333
IT         58000.000000
Name: Salary, dtype: float64

In [16]:
# Many aggregations at once
summary = df.groupby("Department").agg(
    Employees=("EmpID", "count"),
    Avg_Salary=("Salary", "mean"),
    Max_Salary=("Salary", "max"),
    Total_Salary=("Salary", "sum"),
    Avg_Experience=("Experience", "mean"),
)
summary

            Employees    Avg_Salary  Max_Salary  Total_Salary  Avg_Experience
Department
Finance             3  65000.000000       70000        195000            10.0
HR                  3  43333.333333       48000        130000             9.0
IT                  4  58000.000000       75000        232000             6.0

## 6. Normalizing – scaling the data

Salary is in thousands while Experience is in single digits. To compare them fairly we scale them to a common range.

**Min-Max Normalization** (range 0 to 1):
x_new = (x − min) / (max − min)

**Z-score Standardization** (mean 0, std 1):
z = (x − mean) / std

In [17]:
df_norm = df.copy()

# ---- Min-Max normalization ----
for col in ["Age", "Salary", "Experience"]:
    df_norm[col + "_minmax"] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())

df_norm[["Name", "Salary", "Salary_minmax", "Experience", "Experience_minmax"]]

     Name  Salary  Salary_minmax  Experience  Experience_minmax
0    Amit   50000       0.285714           2           0.000000
1    Riya   42000       0.057143           5           0.166667
2   Karan   55000       0.428571           3           0.055556
3    Neha   60000       0.571429          10           0.444444
4     Raj   75000       1.000000          15           0.722222
5  Simran   40000       0.000000           2           0.000000
6     Dev   65000       0.714286           8           0.333333
7  Anjali   52000       0.342857           4           0.111111
8   Rohan   48000       0.228571          20           1.000000
9   Pooja   70000       0.857143          12           0.555556

In [18]:
# ---- Z-score standardization ----
for col in ["Age", "Salary", "Experience"]:
    df_norm[col + "_zscore"] = (df[col] - df[col].mean()) / df[col].std()

df_norm[["Name", "Salary", "Salary_zscore", "Experience", "Experience_zscore"]]

     Name  Salary  Salary_zscore  Experience  Experience_zscore
0    Amit   50000      -0.489151           2          -0.999985
1    Riya   42000      -1.175678           5          -0.508189
2   Karan   55000      -0.060071           3          -0.836053
3    Neha   60000       0.369008          10           0.311471
4     Raj   75000       1.656247          15           1.131131
5  Simran   40000      -1.347310           2          -0.999985
6     Dev   65000       0.798088           8          -0.016393
7  Anjali   52000      -0.317519           4          -0.672121
8   Rohan   48000      -0.660783          20           1.950791
9   Pooja   70000       1.227168          12           0.639335

In [19]:
# Verify the results
print("Min-Max scaled columns -> min and max:")
print(df_norm[["Age_minmax", "Salary_minmax", "Experience_minmax"]].agg(["min", "max"]))

print("\nZ-score columns -> mean and std:")
print(df_norm[["Age_zscore", "Salary_zscore", "Experience_zscore"]].agg(["mean", "std"]).round(4))

Min-Max scaled columns -> min and max:
     Age_minmax  Salary_minmax  Experience_minmax
min         0.0            0.0                0.0
max         1.0            1.0                1.0

Z-score columns -> mean and std:

      Age_zscore  Salary_zscore  Experience_zscore
mean         0.0            0.0                0.0
std          1.0            1.0                1.0

## Conclusion

- **Slicing** was done with `[]`, `iloc` and `loc`.
- **Filtering** was done with boolean conditions using `&`, `|` and `isin()`.
- **Sorting** was done with `sort_values()` on one or many columns.
- **Concatenation** was done row-wise and column-wise with `pd.concat()`.
- **Aggregation** was done with `agg()` and `groupby()`.
- **Normalization** was done with Min-Max (0 to 1) and Z-score (mean 0, std 1) methods, bringing all columns to a comparable scale.